### ISSUE TITLE
Update to work with Ubuntu 14 by changing default variables

### ISSUE THREAD

**Issue by EmilStenstrom** [nicolai86/ansible-phantomjs#4]
Hi,
This module works great with latest Ubunto by just setting:

``` yaml
  vars:
    phantomjs_version: "1.9.8"
    phantomjs_url: "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2"
```

Maybe it would be a good idea to change those, and make your module as compatible with "trusty" on ansible galaxy?
